muzikspirit_front_lifestyle:
    resource: "@MuzikSpiritFrontBundle/Resources/config/modules/lifestyle.yml"

muzikspirit_front_artiste:
    resource: "@MuzikSpiritFrontBundle/Resources/config/modules/artiste.yml"

muzikspirit_front_album:
    resource: "@MuzikSpiritFrontBundle/Resources/config/modules/album.yml"

muzikspirit_front_lyrics:
    resource: "@MuzikSpiritFrontBundle/Resources/config/modules/lyrics.yml"

muzikspirit_front_son:
    resource: "@MuzikSpiritFrontBundle/Resources/config/modules/son.yml"

muzikspirit_front_video:
    resource: "@MuzikSpiritFrontBundle/Resources/config/modules/video.yml"

muzikspirit_front_news:
    resource: "@MuzikSpiritFrontBundle/Resources/config/modules/news.yml"

muzikspirit_front_clip:
    resource: "@MuzikSpiritFrontBundle/Resources/config/modules/clip.yml"

muzikspirit_front_index:
    resource: "@MuzikSpiritFrontBundle/Resources/config/modules/index.yml"
    prefix:   /

muzikspirit_front_ajax:
    resource: "@MuzikSpiritFrontBundle/Resources/config/modules/ajax.yml"
    prefix:   /ajax

muzikspirit_front_statics:
    resource: "@MuzikSpiritFrontBundle/Resources/config/statics.yml"
    prefix:   /
