muzikspirit_front_index:
    path:     /
    defaults: { _controller: MuzikSpiritFrontBundle:Index:index }

muzikspirit_front_statics:
    resource: "@MuzikSpiritFrontBundle/Resources/config/statics.yml"
    prefix:   /
