services:
#    muzik_spirit_front.example:
#        class: MuzikSpirit\FrontBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  muzikspirit_front.twig.hdimage:
    class: MuzikSpirit\FrontBundle\Twig\Extension\HDImageExtension
    tags:
      - { name: twig.extension }
