# Régles config routage
#
# Nom de la route :
# nom_de_l_app_bundle_classe_action
#
# Appel Controleur
# NomduBundle:NomducControleur:Nom de L'action
#
# Ordre de configuration :
# Route -> Controleur -> Vue

muzikspirit_back_artiste_list:
    path:     /list/{page}
    defaults: { _controller: MuzikSpiritBackBundle:Artiste:list, page : 1 }

muzikspirit_back_artiste_searchforward:
    path:     /searchforward/
    defaults: { _controller: MuzikSpiritBackBundle:Artiste:searchforward }

muzikspirit_back_artiste_search:
    path:     /search/{find}
    defaults: { _controller: MuzikSpiritBackBundle:Artiste:search, page : 1 }
    requirements:
        page: \d+

muzikspirit_back_artiste_remove:
    path:     /remove/{id}
    defaults: { _controller: MuzikSpiritBackBundle:Artiste:remove }
    requirements:
        id: \d+
        _method: GET

muzikspirit_back_artiste_add:
    path:     /add
    defaults: { _controller: MuzikSpiritBackBundle:Artiste:add }

muzikspirit_back_artiste_edit:
    path:     /edit/{id}
    defaults: { _controller: MuzikSpiritBackBundle:Artiste:edit }