# Régles config routage
#
# Nom de la route :
# nom_de_l_app_bundle_classe_action
#
# Appel Controleur
# NomduBundle:NomducControleur:Nom de L'action
#
# Ordre de configuration :
# Route -> Controleur -> Vue

muzikspirit_back_carousel_list:
    path:     /list/{page}
    defaults: { _controller: MuzikSpiritBackBundle:Carousel:list, page : 1 }

muzikspirit_back_carousel_searchforward:
    path:     /searchforward/
    defaults: { _controller: MuzikSpiritBackBundle:Carousel:searchforward }

muzikspirit_back_carousel_search:
    path:     /search/{find}
    defaults: { _controller: MuzikSpiritBackBundle:Carousel:search, page : 1 }
    requirements:
        page: \d+

muzikspirit_back_carousel_remove:
    path:     /remove/{id}
    defaults: { _controller: MuzikSpiritBackBundle:Carousel:remove }
    requirements:
        id: \d+
        _method: GET

muzikspirit_back_carousel_add:
    path:     /add
    defaults: { _controller: MuzikSpiritBackBundle:Carousel:add }

muzikspirit_back_carousel_edit:
    path:     /edit/{id}
    defaults: { _controller: MuzikSpiritBackBundle:Carousel:edit }
