# Régles config routage
#
# Nom de la route :
# nom_de_l_app_bundle_classe_action
#
# Appel Controleur
# NomduBundle:NomducControleur:Nom de L'action
#
# Ordre de configuration :
# Route -> Controleur -> Vue

muzikspirit_back_lifestyle_list:
    path:     /list/{page}
    defaults: { _controller: MuzikSpiritBackBundle:Lifestyle:list, page : 1 }

muzikspirit_back_lifestyle_searchforward:
    path:     /searchforward/
    defaults: { _controller: MuzikSpiritBackBundle:Lifestyle:searchforward }

muzikspirit_back_lifestyle_search:
    path:     /search/{find}
    defaults: { _controller: MuzikSpiritBackBundle:Lifestyle:search, page : 1 }
    requirements:
        page: \d+

muzikspirit_back_lifestyle_remove:
    path:     /remove/{id}
    defaults: { _controller: MuzikSpiritBackBundle:Lifestyle:remove }
    requirements:
        id: \d+
        _method: GET

muzikspirit_back_lifestyle_add:
    path:     /add
    defaults: { _controller: MuzikSpiritBackBundle:Lifestyle:add }

muzikspirit_back_lifestyle_edit:
    path:     /edit/{id}
    defaults: { _controller: MuzikSpiritBackBundle:Lifestyle:edit }