# Régles config routage
#
# Nom de la route :
# nom_de_l_app_bundle_classe_action
#
# Appel Controleur
# NomduBundle:NomducControleur:Nom de L'action
#
# Ordre de configuration :
# Route -> Controleur -> Vue

muzikspirit_front_ajax_share_count:
    path:     /share-count/
    defaults: { _controller: MuzikSpiritFrontBundle:Ajax:ShareCount }
