# Régles config routage
#
# Nom de la route :
# nom_de_l_app_bundle_classe_action
#
# Appel Controleur
# NomduBundle:NomducControleur:Nom de L'action
#
# Ordre de configuration :
# Route -> Controleur -> Vue

muzikspirit_front_lifestyle_list:
    path:     /lifestyle/list/{section}/{page}
    defaults: { _controller: MuzikSpiritFrontBundle:Lifestyle:list, section : all, page : 1 }

muzikspirit_front_lifestyle_view:
    path:     /lifestyle/{slug}/{id}
    defaults: { _controller: MuzikSpiritFrontBundle:Lifestyle:view, page : 1 }
    requirements:
      id: \d+
      _method: GET