# Régles config routage
#
# Nom de la route :
# nom_de_l_app_bundle_classe_action
#
# Appel Controleur
# NomduBundle:NomducControleur:Nom de L'action
#
# Ordre de configuration :
# Route -> Controleur -> Vue

muzikspirit_front_news_list:
    path:     /news/list/{section}/{page}
    defaults: { _controller: MuzikSpiritFrontBundle:News:list, section : all, page : 1 }

muzikspirit_front_news_view:
    path:     /news/{slug}/{id}
    defaults: { _controller: MuzikSpiritFrontBundle:News:view, page : 1 }
    requirements:
      id: \d+
      _method: GET