# Régles config routage
#
# Nom de la route :
# nom_de_l_app_bundle_classe_action
#
# Appel Controleur
# NomduBundle:NomducControleur:Nom de L'action
#
# Ordre de configuration :
# Route -> Controleur -> Vue

muzikspirit_back_image:
    resource: "@MuzikSpiritBackBundle/Resources/config/modules/image.yml"
    prefix:   /image

muzikspirit_back_news:
    resource: "@MuzikSpiritBackBundle/Resources/config/modules/news.yml"
    prefix:   /news

muzikspirit_back_dashboard:
    path:     /
    defaults: { _controller: MuzikSpiritBackBundle:Default:index }
