services:
#    muzik_spirit_back.example:
#        class: MuzikSpirit\BackBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  # Service de message de notification de session
  muzikspirit_back.notification:
    class: MuzikSpirit\BackBundle\Notification\Notification
    arguments: ["@session"]

  # Service de connexion avec les réseaux sociaux
  muzikspirit_back.oauth_aware.user_provider:
    class: MuzikSpirit\BackBundle\Provider\OAuthUserProvider

  # Service de mise à jour de la date de connexion
  muzikspirit_back.listener.auth:
    class: MuzikSpirit\BackBundle\Listener\AuthListener
    arguments: ["@doctrine.orm.entity_manager","@security.context"]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onAuthentificationSuccess }

  # Service de mise a jour des articles
  muzikspirit_back.listerner.articles:
    class: MuzikSpirit\BackBundle\Listener\ArticleListener
    tags:
      # name: correspond au mecanisme ou ma classe sera affecté ici dans un mécanisme de doctrine
      # event: sera l'événement qui déclenchera notre méthode qui exécutera nos actions
      - { name: doctrine.event_listener, event: prePersist, method: prePersist }
      - { name: doctrine.event_listener, event: preRemove, method: preRemove }
      - { name: doctrine.event_listener, event: postPersist, method: postPersist }


  # Service de gestion des autorisations des utilisateurs
  muzikspirit_back.voter:
    class: MuzikSpirit\BackBundle\Security\Authorization\Voter\OwnerVoter
    tags:
      - { name: security.voter }
  # Service de BBcode
  muzikspirit_back.twig.bbcode:
    class: MuzikSpirit\BackBundle\Twig\Extension\BbcodeExtension
    tags:
      - { name: twig.extension }

  # Service de Gestion d'image pour suppression
  muzikspirit_back.image:
          class: MuzikSpirit\BackBundle\Controller\ImageController